---
# handlers file for redis

- name: Restart Redis please
  ansible.builtin.systemd:
    name: redis
    state: restarted
    daemon_reload: yes

- name: Stop Redis please
  ansible.builtin.systemd:
    name: redis
    state: started
    daemon_reload: yes

- name: Start Redis please
  ansible.builtin.systemd:
    name: redis
    state: stopped