---
# handlers file for kafka
- name: Restart Kafka please
  ansible.builtin.systemd:
    name: kafka
    state: restarted
    daemon_reload: yes

- name: Stop Kafka please
  ansible.builtin.systemd:
    name: kafka
    state: started
    daemon_reload: yes

- name: Start Kafka please
  ansible.builtin.systemd:
    name: kafka
    state: stopped