---
# vars file for kafka
kafka_unit_path: /etc/systemd/system/kafka.service
KafkaEnv: "JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64"
KafkaExecStart: "/home/{{ kafka_user }}/installed/kafka_2.13-3.3.1/bin/kafka-server-start.sh /usr/local/kafka/config/server.properties"
KafkaExecStop: "/home/{{ kafka_user }}/installed/kafka_2.13-3.3.1/bin/kafka-server-stop.sh"